source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'VirgilSDKApp' do
	pod 'VirgilFoundation', '1.4.1-rc-1.3.0'
    
    target 'VirgilSDKTests' do
        inherit! :search_paths
    end
end

target 'VirgilSDKAppSwift' do
	pod 'VirgilFoundation', '1.4.1-rc-1.3.0'
    
    target 'VirgilSDKSwiftTests' do
        inherit! :search_paths
    end
end