source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'VirgilSDKApp' do
	pod 'VirgilCrypto', :git => 'https://github.com/VirgilSecurity/virgil-foundation-x.git', :branch => '2.0.0-beta6'

    target 'VirgilSDKTests' do
        inherit! :search_paths
    end
end

target 'VirgilSDKAppSwift' do
	pod 'VirgilCrypto', :git => 'https://github.com/VirgilSecurity/virgil-foundation-x.git', :branch => '2.0.0-beta6'
    
    target 'VirgilSDKSwiftTests' do
        inherit! :search_paths
    end
end
