platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'VirgilFirebaseChat' do
  pod 'VirgilSDK', '~>3.1'
  pod 'Firebase', :subspecs => ['Database']
  pod 'SlackTextViewController'
  pod 'XAsync', '~>2.0'
end
