name: docs

on:
  push:
    branches:
      - '*'

jobs:
  GenDocs:
    name: Generate documentation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Docs
        run: ./CI/publish-docs.sh
