name: tests

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'develop'
      - 'release/**'
  pull_request:
    branches:
      - '**'

jobs:
  Tests:
    name: Tests
    runs-on: macos-latest
    env:
      PROJECT: VirgilSDK.xcodeproj
    strategy:
      matrix:
        include:
          - destination: "platform=iOS Simulator,name=iPhone 16,arch=arm64"
            prefix: "iOS"
            test: "1"
          - destination: "arch=x86_64"
            prefix: "macOS"
            test: "1"
          - destination: "platform=tvOS Simulator,name=Apple TV 4K (3rd generation),arch=arm64"
            prefix: "tvOS"
            test: "1"
          - destination: "platform=watchOS Simulator,name=Apple Watch Series 10 (46mm),arch=arm64"
            prefix: "watchOS"
            test: "0"
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt tests config
        run: ./CI/decrypt-config.sh
        env:
            ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
            ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
      - name: Run ${{ matrix.prefix }} Tests
        uses: nick-fields/retry@v2
        with:
          max_attempts: 20
          timeout_minutes: 30
          retry_on: error
          command: |
            set -o pipefail
            SCHEME="VirgilSDK ${{ matrix.prefix }}"

              if [ "${{ matrix.test }}" == "1" ]; then
                  # Build & Test
                  xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -destination "${{ matrix.destination }}" -configuration Debug test | xcpretty;
              else
                  # Build Only
                  xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -destination "${{ matrix.destination }}" -configuration Release clean build | xcpretty;
              fi
  SPM:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt tests config
        run: ./CI/decrypt-config.sh
        env:
            ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
            ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
      - name: SPM test
        run: |
            brew install coreutils # install 'timeout' utility
            swift --version
            # fix for Swift Package Manager when it fails to download binary targets
            timeout 15m bash -c 'until swift build; do rm -fr .build && sleep 10; done'
            swift test
